/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2012-11-11 13:44:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>Ex1</title>\r\n");
      out.write("\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "share/header.jsp", out, false);
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\t");
	if (request.getMethod() == "POST") { 
      out.write("\r\n");
      out.write("\t\t <div class=\"well\">\r\n");
      out.write("\t\t  <ul>\r\n");
      out.write("\t\t    <li>이름 : ");
      out.print(request.getParameter("name"));
      out.write("</li>\r\n");
      out.write("\t\t    <li>비밀번호 : ");
      out.print(request.getParameter("pwd"));
      out.write("</li>\r\n");
      out.write("\t\t    <li>E-mail : ");
      out.print(request.getParameter("email"));
      out.write("</li>\r\n");
      out.write("\t\t    <li>Country : ");
      out.print(request.getParameter("country"));
      out.write("</li>\r\n");
      out.write("\t\t    <li>성별 : ");
      out.print(request.getParameter("gender"));
      out.write("</li>\r\n");
      out.write("\t\t    <li>좋아하는 그룹 :\r\n");
      out.write("\t\t      <ul>\r\n");
      out.write("\t\t      ");
 
		      if (request.getParameter("favorites") != null) {
		        for(String name: request.getParameterValues("favorites")) {
		          out.println("<li>" + name + "</li>");
		        }
		      }
		      
      out.write("\r\n");
      out.write("\t\t      </ul> \r\n");
      out.write("\t\t    </li>\r\n");
      out.write("\t\t    <li>메모 : ");
      out.print(request.getParameter("memo"));
      out.write("</li>\r\n");
      out.write("\t    </ul>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("  ");
} else { 
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("\t\t  <h1>Form Handling Example</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t  <form class=\"form-horizontal\" method=\"post\">\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<div id=\"legend\">\r\n");
      out.write("\t\t\t\t\t<legend>Sign up</legend>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"name\">Name</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"홍길동\" name=\"name\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"pwd\">Password</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"pwd\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"email\">E-mail</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"email\" placeholder=\"hong@abc.com\" name=\"email\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\">Country</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"country\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"KR\">Korea</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"US\">USA</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"JA\">Japan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"CN\">China</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\">Gender</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"radio\"> \r\n");
      out.write("\t\t\t\t\t\t  <input type=\"radio\" value=\"m\" name=\"gender\" checked=\"checked\"> male\r\n");
      out.write("\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t<label class=\"radio\"> \r\n");
      out.write("\t\t\t\t\t\t  <input type=\"radio\" value=\"f\"\tname=\"gender\"> female\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\">Favorites</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox\"> \r\n");
      out.write("\t\t\t\t\t\t  <input type=\"checkbox\" name=\"favorites\" value=\"IU\"> IU\r\n");
      out.write("\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox\"> \r\n");
      out.write("\t\t\t\t\t\t  <input type=\"checkbox\" name=\"favorites\" value=\"2NE1\"> 2NE1\r\n");
      out.write("\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox\"> \r\n");
      out.write("\t\t\t\t\t\t  <input type=\"checkbox\" name=\"favorites\" value=\"Sistar\"> Sistar\r\n");
      out.write("\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox\"> \r\n");
      out.write("\t\t\t\t\t\t  <input type=\"checkbox\" name=\"favorites\" value=\"Kara\"> Kara\r\n");
      out.write("\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox\"> \r\n");
      out.write("\t\t\t\t\t\t  <input type=\"checkbox\" name=\"favorites\" value=\"Girl's generation\"> Girl's\tgeneration\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\">Memo</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textarea\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"memo\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-actions\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t  </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "share/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
